@startuml
left to right direction

package Domain {
    package Common {
        class AuditableEntity {

        }

        class ApplicationUser {

        }
    }

    package Entites {
        class Address {

        }

        class Booking {

        }

        class Category {

        }

        class ContactInfo {

        }

        class MarketInstance {

        }

        class MarketTemplate {

        }

        class Merchant {
            
        }

        class Organiser {

        }

        class RefreshToken {

        }

        class Stall {

        }

        class StallType {

        }

        class User {

        }
    }

    package Enums {
        enum ContactInfoType {

        }
    }

    package EntityExtensions {

    }

    package Exceptions {

    }
}
@enduml