@startuml
class MarketTemplate {

}

class Stall {

}

class MarketInstance {

}

class StallMarketInstance {

}

MarketTemplate "1" --"1..*" MarketInstance
MarketTemplate "1" -- "1..*" Stall
Stall "1" -- "*" StallMarketInstance
MarketInstance "1" -- "*" StallMarketInstance


@enduml